### ISSUE TITLE
Is it possible to style external links?

### ISSUE THREAD

**Issue by rk-kontur** [felixqueisler/Obsidian-FileLink-Styling#1]
I find this CSS very interesting but would like to see styling options for external links to my harddrive. They would be created by Drag/Drop using CTRL and look like this:

[huh.pdf](file:///C:%5CUsers%5Cremote%5CDownloads%5Chuh.pdf)

I would like to have the links a different color and an arrow pointing to the right, if possible.

**Comment by felixqueisler** [comment]
Thank you for the request. Support for external files in the local filesystem was completed with commit https://github.com/felixqueisler/Obsidian-FileLink-Styling/commit/354fc02e10f662f5d696d3b0971b5f6fd69554d7

It brings:
* Added and specific styling for external local files
* Hue shifted colors for the external links to make them better discernible from vault files. Hues shifted because of a lack of secondary accent colors in obsidian variables.
* A new icon for external links
* torrent icon support (internal linking)

**Comment by felixqueisler** [comment]
<img width="544" alt="Bildschirmfoto 2024-04-28 um 17 03 53" src="https://github.com/felixqueisler/Obsidian-FileLink-Styling/assets/3536483/0a186dfb-5dd0-49a1-b413-caecb100cd9e">
